### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by tomleb3** [davidarroyo1234/Simple-AntiAFK#1]
Wasn't sure how to get a hold of you lol.
There are some stuff I would like to run by you.
Is there any way we can keep in contact?

Email / WhatsApp / IG / whatever else?

**Comment by davidarroyo1234** [comment]
> Wasn't sure how to get a hold of you lol. There are some stuff I would like to run by you. Is there any way we can keep in contact?
> 
> Email / WhatsApp / IG / whatever else?

I have send you an email

**Comment by tomleb3** [comment]
Got it. Thanks!
